CREATE DATABASE IF NOT EXISTS webgis_pertanian CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE webgis_pertanian;

CREATE TABLE IF NOT EXISTS users (
 id INT AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(50) NOT NULL UNIQUE,
 password VARCHAR(255) NOT NULL,
 nama_lengkap VARCHAR(100) NOT NULL,
 role ENUM('admin','user') DEFAULT 'user',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sawah (
 id INT AUTO_INCREMENT PRIMARY KEY,
 nama_lahan VARCHAR(150) NOT NULL,
 luas DECIMAL(12,2) DEFAULT 0,
 varietas VARCHAR(100),
 produksi DECIMAL(12,2) DEFAULT 0,
 kelompok_tani VARCHAR(150),
 kondisi_irigasi VARCHAR(100),
 jenis_tanah VARCHAR(100),
 keterangan TEXT,
 geometry LONGTEXT,
 petak_id VARCHAR(30) NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS irigasi (
 id INT AUTO_INCREMENT PRIMARY KEY,
 nama_irigasi VARCHAR(150) NOT NULL,
 panjang DECIMAL(12,2) DEFAULT 0,
 kondisi VARCHAR(100),
 sumber_air VARCHAR(150),
 keterangan TEXT,
 geometry LONGTEXT,
 petak_id VARCHAR(30) NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tanah (
 id INT AUTO_INCREMENT PRIMARY KEY,
 jenis_tanah VARCHAR(150) NOT NULL,
 luas DECIMAL(12,2) DEFAULT 0,
 karakteristik TEXT,
 keterangan TEXT,
 geometry LONGTEXT,
 petak_id VARCHAR(30) NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE sawah ADD COLUMN IF NOT EXISTS petak_id VARCHAR(30) NULL;

INSERT INTO users (username,password,nama_lengkap,role)
SELECT 'admin','admin123','Administrator','admin'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username='admin');
